# Site settings
title: Vodite računa
short_title: Vodite računa
description: |
    Portal su pokrenuli Centar za razvoj neprofitnog sektora (CRNPS) i Centar za istraživanje, transparentnost i odgovornost, (CRTA), i ima za cilj da ohrabri građane, medije i sve zainteresovane da razumeju pitanja budžeta i da vode računa o tome kako vlasti upravljaju javnim sredstvima. 
baseurl: ""#http://crtarsorg.github.io/vodite-racuna"
url: "http://crtarsorg.github.io/vodite-racuna" # the base hostname & protocol for your site
github_username:  crtarsorg
author: Open Data Kosovo
github_repo:  vodite-racuna
paypal: admin@okfn.org
contact: https://discuss.okfn.org/c/network-and-community/open-data-handbook

devs:
  -
      name: Open Data Kosovo
      github: mintcanary

contributors:
  -
      name: Rufus Pollock
      link: http://rufuspollock.org/

supporters:
  -
    name: Shuttleworth Foundation
    logo: shuttleworth.png
    footer_logo: shuttleworth-footer.png
    url: https://www.shuttleworthfoundation.org/
  -
    name: The World Bank
    logo: worldbank.png
    footer_logo: worldbank-footer.png
    url: http://www.worldbank.org/


#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts


related_projects:
  -
      name: OpenGovernmentData.org
      link: http://opengovernmentdata.org/
  -
      name: The DataHub
      link: http://datahub.io/
  -
      name: DataCatalogs.org
      link: http://datacatalogs.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/
  -
      name: Introducing Open Data
      link: http://okfn.org/opendata/